#just for tac
statistics=true
job=AgenciesBackOnTrack
jobVersion=0.1
date=2026-04-07 075427985
contextName=Default
jobId=_7tIyYCFMEfGhTIXORtm4Bw
jobType=Standard
framework=
projectId=0
applyContextToChildren=false
project=TEST_MSPR
branch=branches/
cmdLineVersion=7.3.1.20200219_1130
